### ISSUE TITLE
Assignee was already taken

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#201]
**Describe the bug**
The $assignAssignee built-in failed at:
https://github.com/reviewpad/reviewpad/runs/7579526371?check_suite_focus=true

**Expected behavior**
No failure.

**Comment by denizzengin** [comment]
Hi @marcelosousa,
Could you produce the above error, actually i didn't. Refer git api tells always returns "201 created ". Also they say that "Usernames of people to assign this issue to. NOTE: Only users with push access can add assignees to an issue. Assignees are `**silently**` ignored otherwise.", is there any relation go-github v42 ?

**Comment by marcelosousa** [comment]
@denizzengin thanks for this information 🙌  I also couldn't reproduce this issue so I'm closing it for now!
