### ISSUE TITLE
Open issues for each event type handling

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#357]
At the moment, we only support a few event types:
https://github.com/reviewpad/reviewpad/blob/main/handler/processors.go#L269

This issue is to investigate which event types make sense for Reviewpad to handle, as in, computing the pull requests or issues that could be impacted and to open issues for each of those events.

Those issues should be linked to this one.

**Comment by shay2025** [comment]
Reviewpad may make sense to handle the following events:
- [`installation`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#installation)[`installation_repostiories`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#installation_repositories): makes sense for Reviewpad to compute all pull requests and issues upon its installation. 

- [`fork`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#fork): would Reviewpad run in the forked repository or in the repository that was forked?

- [`label`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#label): this may cause Reviewpad to be runned many times because if Reviewpad runs and adds a label it will be triggered again and so on...

- [`organization`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#organization)[`org_block`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#org_block): if a pull request/issue has an assignee and that assignee is removed from the org or blocked, will GitHub automatically remove him from any pull requests/issues that they are associated with?

- [`project`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#project)[`project_card`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#project_card)[`project_column`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#project_column)[`project_v2_item`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#projects_v2_item): an usecase for Reviewpad handling would be if a pull request or issue is added to a project, Reviewpad is triggered and can label that same issue/pull request with a label which title is the column it is in.

- [`repository_dispatch`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_dispatch)[`workflow_dispatch`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch): does it make sense for Reviewpad to be run manually?

- [`team`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#team)[`team_add`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#team_add) **TBD**

**Comment by marcelosousa** [comment]
Specify use cases that justify the support for any of the events missing.
