### ISSUE TITLE
Error on using sprintf with ArrayType arguments

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#583]
**Describe the bug**
The following aladino expression: 
```
$warn($sprintf("Request a 1:1 with security team: %s", [$join(["marcelosousa", "ferreiratiago"], " - ")]))
``` 

Is not being correctly handled by interpreter because we get the error: `type inference failed: mismatch in arg types on sprintf`.

I already checked that the AST seems to be correct so the investigation needs to focus in the type inference.

I think the root cause is that `sprintf` is expecting an `ArrayOfType(String)` while the type of `["marcelosousa", "ferreiratiago"]` is an `ArrayType(String)`. 

This is likely the cause because the following expression works:

```
$warn($sprintf("Request a 1:1 with security team: %s", [$group("team", " - ")]))
``` 

Because `$group()` returns an `ArrayOfType(String)`.

**Comment by zolamk** [comment]
After an investigation into what's happening when using `$join`, I don't think this is caused by type differences because an `ArrayType(String)` should be equal to `ArrayOfType(String)` if the elements are equals, I believe what is causing this is the [addDefaultJoinSeparator](https://github.com/reviewpad/reviewpad/blob/5a3396383de003a028f439cd69f92e7cecd31f74/engine/transform.go#L76) function, as you can see on https://go.dev/play/p/f_1DSSmAZps the function adds the separator even if one is provided causing

`$warn($sprintf("Request a 1:1 with security team: %s", [$join(["marcelosousa", "ferreiratiago"], " - ")]))`

to become

`$warn($sprintf("Request a 1:1 with security team: %s", [$join(["marcelosousa", "ferreiratiago"], " - ")], " "))`

and causing the `mismatch in arg types...` error

**Comment by zolamk** [comment]
The reason why this format work is `$warn($sprintf("Request a 1:1 with security team: %s", [$join($group("team"), " - ")]))` because it's not triggering the part of the regular expression that's putting the default in the wrong place.
