### ISSUE TITLE
`$triggerWorkflow` built-in is failing

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#603]
**Describe the bug**
When trying to add this workflow https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues#creating-the-workflow replacing the `on` field with `workflow_dispatch` as said in https://docs.reviewpad.com/guides/built-ins#triggerworkflow, the following error is returned:
`403 Resource not accessible by integration []`

**To Reproduce**
1. Add the workflow https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues#creating-the-workflow and replace the value of the `on` field with `workflow_dispatch` as pointed out in https://docs.reviewpad.com/guides/built-ins#triggerworkflow.
2. Open a pull request.

**Expected behavior**
The built-in should not fail.

**Comment by marcelosousa** [comment]
This issue was related to permissions on the GitHub app.

The permissions were updated with the following message to the users:

```markdown
Hey there :wave: 

This update requests permissions to read and write GitHub Actions workflows.

This is required to use the built-in [triggerWorkflow](https://docs.reviewpad.com/guides/built-ins/#triggerworkflow).
```

@shay2025: for upcoming issues, we should understand if the issue is related to the actual logic of the built-in or something to do with the GitHub Action/App. IMO, if it is not related to the logic, we shouldn't open the issue in this repository.
